import "./globals.css";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: "800",
  variable: "--font-jakarta",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fetchCache =
  process.env.NODE_ENV === "production" ? "auto" : "force-no-store";

storyblokInit({
  accessToken: "ckbY4lg0OtsQ9U6PCjI7rgtt",
  use: [apiPlugin],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <StoryblokProvider>
        <html
          lang="en"
          className={`${inter.variable} ${plus_jakarta_sans.variable}`}
        >
          <body className="font-sans">
            <header className="bg-main">
              <nav className="max-w-5xl mx-auto px-4 py-8 w-full flex justify-between items-baseline">
                <Link href={"/"}>Home</Link>
                <Link href={"/tours"}>Browse Tours</Link>
              </nav>
            </header>
            {children}
            <footer className="bg-secondary">
              <div className="max-w-5xl mx-auto px-4 py-4 w-full">
                <p className="opacity-80">&copy; Copyright 2023 Taiwan Tours</p>
              </div>
            </footer>
          </body>
        </html>
      </StoryblokProvider>
    </>
  );
}
